### ISSUE TITLE
Multiple Ranges Stacked

### ISSUE THREAD

**Issue by rob2791** [ryan-d-williams/MMM-GoogleSheets#1]
Nice project! I've got it running, instructions were easy to follow, only took about 10 minutes before I had it up. I'm pulling data from my budget spreadsheet, look up TillerHQ if you're interested. 

Is there any way to have it pull multiple ranges? Maybe something like "A1:B7&C1:D7", where the second range would be just underneath it. I'm going to try putting in a new module with my second range but I figured I'd ask and give you some feedback. :) Cheers.

**Comment by ryan-d-williams** [comment]
Thank you for the feedback!

That's a good feature idea, I'll go ahead and add it when I get a chance.

If you're looking for a quick fix, you can create a new sheet in your spreadsheet and concatenate the two ranges into one range to show on the mirror (or even a new spreadsheet that references the existing spreadsheet if you don't want to adjust anything in the original spreadsheet). 

Your use case seems like a great use of the module. If you're comfortable sharing the data in your spreadsheet, please send me screenshot of the module output and I can add it as an example in the readme.

**Comment by ryan-d-williams** [comment]
@rob2791 the more I think about this feature, the more I think it would actually make more sense to just create a new sheet that incorporates all the data you need and add that sheet to your magic mirror. The reason being the two different ranges (or many ranges for that matter) will have to account for different sizes, styling, merges, etc. It seems the most logical answer is to just allow one range, and the user can combine ranges as needed to show on the magic mirror. 

If you think there is a valid use case for stacking ranges instead of making a new sheet please let me know and I can add that feature.

**Comment by ryan-d-williams** [comment]
@rob2791 I'm going to go ahead and close this issue based on what I said above (just creating a new sheet with the stacked data yourself rather than adding the complexity of two different configurations). If you have additional reasons you think this would be a good feature please let me know!
