### ISSUE TITLE
Module Displayed, Sheet Not

### ISSUE THREAD

**Issue by jonnyscott10** [ryan-d-williams/MMM-GoogleSheets#2]
Hi, the module seems to be loading okay no errors to be seen in the dev console but the sheet is not loading as can be seen on the following image

![image](https://user-images.githubusercontent.com/61477741/85960439-537d2000-b99b-11ea-98d1-6cfa4c54b0f5.png)

**Comment by ryan-d-williams** [comment]
@jonnyscott10 do you mind passing what your configuration looks like for the module? If your sheet data is private you can leave out the link otherwise I can try it out to see what's going wrong.

**Comment by jonnyscott10** [comment]
{
  					module: "MMM-GoogleSheets",
 					header: "Schedule",
  					position: "top_left",
 					config: {
    						url:"https://script.google.com/macros/s/AKfycbyOLx0LB8ro-g8RiW4LAf7fsCbWeKgUUHfOSAp5wCz_kkVElimZ/exec",
    						sheet: "Sheet1",
    						range: "A1:B10",
    						updateInterval: 1, // minutes
    						},

**Comment by ryan-d-williams** [comment]
@jonnyscott10 it looks like you have a permission issue. When I click on your link, it requires a login (which it should not). If it requires a login when you click on it, that means it would also require a login when it is hit by magic mirror. 

You need to remove the permissions of your script to get it to work. My best guess without seeing the way you set up the file is you missed this step in the installation procedures:
`In the menu that pops up, change "Who has access to the app:" to Anyone, even anonymous`

Without this step, it would require login anytime you hit the link. With this step, anyone can run it just by hitting the link.

Let me know if that works / doesn't work for you.

**Comment by jonnyscott10** [comment]
Hi, yes it seems it was set to public but not as me as a user, the module now shows undefined and I am currently researching this issue, if you want to have a look now you should be able to look at the script without logging in

**Comment by ryan-d-williams** [comment]
@jonnyscott10 when I run magic mirror with your config it works fine. Are you still having issues?

**Comment by jonnyscott10** [comment]
@ryan-d-williams it currently is still showing undefined on the module

**Comment by kalecream** [comment]
> @ryan-d-williams it currently is still showing undefined on the module

I'm also having this issue.

**Comment by ryan-d-williams** [comment]
@kalecream can you please post the config you are using?

**Comment by ryan-d-williams** [comment]
@jonnyscott10 I have tried that exact config again and it is working fine. Can you try making sure you config matches what you have above? If that exact config is working for me and not for you it is likely an issue with your setup.

**Comment by kalecream** [comment]
```
{
			module: "MMM-GoogleSheets",
			header: "Google Sheets",
			position: "top_center",
			config: {
				url: "[redacted]",
				sheet: "Dashboard",
				range: "C8",
			}
},
```

However, I'm sure the problem isn't our configuration, since we are getting this error (click on image below) from the google script library. It keeps pointing back to line 11 of the code from my last message.
![Screenshot from 2021-02-16 17-07-47](https://user-images.githubusercontent.com/44611104/108127841-d7466280-7079-11eb-8e21-969acd7f1d66.png)

**Comment by ryan-d-williams** [comment]
@kalecream clicking on the link it provides should provide an error. This is because you are not providing the sheet and range to the url, so it errors. If you want to have the link not produce an error, you can try the link with this format:
url?sheet={sheetname}&range={range} so for example, the url from @jonnyscott10 above would be
[https://script.google.com/macros/s/AKfycbyOLx0LB8ro-g8RiW4LAf7fsCbWeKgUUHfOSAp5wCz_kkVElimZ/exec?sheet=Sheet1&range=A1:B10](https://script.google.com/macros/s/AKfycbyOLx0LB8ro-g8RiW4LAf7fsCbWeKgUUHfOSAp5wCz_kkVElimZ/exec?sheet=Sheet1&range=A1:B10)

Notice that if you click that link, you will get data as expected.

If you try to reformat your url with the correct format, what does it return? I cannot try it for you as you have not provided your link (totally find if it has sensitive data, you will just have to do the debugging steps yourself)

**Comment by ryan-d-williams** [comment]
@kalecream also note that the module does this url formatting for you automatically based on the config file. What I said above is just for you to see if the url itself is working or not, you do not need to change your module at all.

**Comment by Firephly** [comment]
@ryan-d-williams Firstly excellent work on this, or at least so far and potentially. 

I to had the line 11 problem but it turned out im dumb and put the book name not the sheet name.

It all works if i type the url in browser with the range and sheet parameters but not in the module.
I see the message

missing required parameter:url
missing required parameter:sheet
missing required parameter:range

![sheets](https://user-images.githubusercontent.com/86256911/122807854-ff61fe80-d2c3-11eb-8a79-ec3faaefbc73.JPG)

 i have reloaded module and copied and pasted a few times to check for errors, what am i missing?

Thanks in advance.
