### ISSUE TITLE
Could not load config file. Error found: Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by dpappo** [ryan-d-williams/MMM-GoogleSheets#21]
Firstly, thank you for creating and sharing this software. It's excellent.

Post-install and config, launching MM lead to `WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'`

I've temporarily fixed the issue on my mirror by running `npm install request` in the module's directory.

You'll probably need to include a package.json with a dependency definition for the request module.

Cheers and thanks for your lovely module!

**Comment by ryan-d-williams** [comment]
@dpappo thanks for pointing this out. It looks like the newest release of MM does not come with the request module like it used to. I'm going to leave this issue open until I get a chance to update the module / instructions.

For now, if you are reading this issue, then you must navigate to the module folder (MMM-GoolgeSheets) and run
`npm install requst`
In order to get the module to work

**Comment by dpappo** [comment]
Perfect, thanks @ryan-d-williams. I would also recommend adding a general `npm install` command to the readme before or after the `npm install request` command, which I ran for the install.

Thanks again for your work here!

**Comment by ryan-d-williams** [comment]
Fixed by #32
