### ISSUE TITLE
GoogSheets not running - black screen

### ISSUE THREAD

**Issue by ma-melch** [ryan-d-williams/MMM-GoogleSheets#26]
Dear Ryan, at first i want to thank you for developing the googlesheets module. I am very interested in this module. Unfortunately i am not able to get it to work. After adding the configuration to the config file the mirror does not start. I think i made some mistakes in creating the sheet in google. Maybe someone can explain the process in google more detailed or can translate it in german.  Help is very apreciated. Thank you!

**Comment by Old-Engineer** [comment]
The instructions in the readme.md file are no longer accurate, probably because Google have changed their process in setting up the web app and getting to the necessary link.
Try these in the attached file instead.
[GoogleSheets Updated Readme.pdf](https://github.com/ryan-d-williams/MMM-GoogleSheets/files/11929851/GoogleSheets.Updated.Readme.pdf)

**Comment by ryan-d-williams** [comment]
@ma-melch unfortunately it has been a long time since I initially created the module. @Old-Engineer is correct, there have been lots of changes to the interface since then.

@Old-Engineer thank you for creating that! I plan to go through and actually update the instructions in the future, but if you want to submit a pull request with new instructions I will happily merge it in.

**Comment by ryan-d-williams** [comment]
@ma-melch @Old-Engineer even more changes have been made to google apps script since this issue was last active. I went through and updated the README to reflect the most recent version (with pictures). It should be relatively easy now to follow the instructions. Feel free to reopen this issue if you have any further problems.
