### ISSUE TITLE
Why does this need to access ALL of my Sheets?

### ISSUE THREAD

**Issue by brandonfake69** [ryan-d-williams/MMM-GoogleSheets#28]
Please change the scope to https://www.googleapis.com/auth/spreadsheets.currentonly so that it only accesses the current Sheet. Best practices in programming is to limit the scope of such requests. thanks

**Comment by ryan-d-williams** [comment]
@brandonfake69 great idea! These options were unfortunately not available when I built the application (you had not direct scope control back then).

**Comment by ryan-d-williams** [comment]
@brandonfake69 Unfortunately I tried to make this change today, and it looks like it is no longer possible.

The link you sent is dead, and the new list of scopes no longer has an option for speadsheets.currentonly (https://developers.google.com/identity/protocols/oauth2/scopes#script). The only two available options are readonly and the scope the library currently uses. Unfortunately readonly cannot be used because this would not allow the library to be used with formulas while the sheet is closed (see #22).

I'm going to close this for now. Feel free to open it if you see a scope I missed. I'll keep an eye on the scopes in the future and update the library if they reinstate currentonly.
