### ISSUE TITLE
LOVE THIS IDEA!!  I just can't seem to get it to work

### ISSUE THREAD

**Issue by brianbslp** [ryan-d-williams/MMM-GoogleSheets#52]
I have followed the directions, but can't seem to get the Google Web app link to work.  When I click on the link it says: Sorry, unable to open the file at this time.

Please check the address and try again.

When I click on the library link it says:  You do not have access to library 1QvOy7bDn6_-DMO3YSYHh2-DA-ngxFXXxwOZ6Uf2e8PKIDsd-l9mQof1o, used by your script, or it has been deleted.

I'm not sure what I'm missing and any help would be appreciated!

**Comment by ryan-d-williams** [comment]
@brianbslp can you share your config? If you can I can take a look and see if I can help.

When you click the link, it's not expected to work on its own. The link requires the right parameters that are inserted by the library before sending the request. The error you are getting is not normal though so I can take a look.

I'm not sure what you mean by "library link". Where are you seeing that? The ID for the library is slightly different than what you entered so maybe it is a copy-paste issue? The library ID is `1a6A0PqVebZUkbUC8lq__djKv6y9wZyF8y7v8dIkPpV7-mdmxwrt5SxDK`.

If you include some screenshots of where you are copying your web app link from it can help me debug with you.

**Comment by brianbslp** [comment]
Thank you so much for the quick response and help @ryan-d-williams! 

I've attached the screenshots and a copy of my config code below.  I did blur out the links but they are all the same and the library did come up exactly as it was in the instructions.  When I run MM it gives me back the error of "There was an error in the request:  Request failed.  Check the URL and logs for more information.  When I look at the error it says [ERROR] [MMM-Google-Sheets] **ERROR** there was an error with the request at (Current date).  This URL should work in your browser:  When I click on the link it shows the values in the table along with background colors, height, width, and font styles.  

Config:

{
  module: "MMM-GoogleSheets",
  header: "Speech Student and Specials Day",
  position: "middle_center",
  config: {
    url: "https://script.google.com/macros/s/XXXXXX/exec",
    sheet: "STUDINFOSHEET",
    range: "H4:K40",
  }
},

![Deploy with links](https://github.com/user-attachments/assets/4716658c-f4e7-46f8-a43b-23b2e000e6fe)

**Comment by ryan-d-williams** [comment]
@brianbslp happy to help! 

Without seeing the actual link, it will be very difficult for me to help figure out the problem. I understand the data may be sensitive so we have a few options to where I can still help you. 

1. You can delete the sensitive data and put some fake information in. Then you can share the link and I can take a look. When we're done you can redeploy (which changes the link) and put your sensitive data back in.
2. You can create a new spreadsheet with fake data and follow the instructions again and share the link with me so I can take a look. This one would require you to follow the steps again which I know can be annoying.

It may also be worth making sure you are deployed to "Anyone". Check the readme for the "Who has access" steps during deployment. If the script is throwing an error (evidenced by the log statement) that usually (but not always) means a permission issue. If you click the link and it works fine (in chrome I'm assuming), it could mean that you are now logged in to your Google account in Chrome so you have deployed for only your account rather than "Anyone". You can check if this is the problem very quickly by opening the link in an incognito window. If you can no longer see the data then you have deployed incorrectly and you need to update it according to the readme instructions. **This is the most probable issue so I would start with the incognito test before either of the options above**.

**Comment by brianbslp** [comment]
Thank you again @ryan-d-williams. 

I have created a new Google Sheet with fake information and will attach the New Deployment information screenshot below along with the updated config information.  My previous Google sheet had a lot of formulas making up the information so I have simplified this current one to just information in the cells, yet I still can't get it to work.  I believe I have meticulously followed your instructions, and everything on the Google Sheet side seems to have gone through exactly as stated in your instructions.  When I selected the correct Library I then hit New Deployment and got the permissions request which I allowed.  Then I selected my email and made sure that Anyone has access.  I have provided an additional updated image of my management deployments in hopes that it will help.   

When I click on the error link it comes back as almost HTML code, but not the actual cells.  I have tried it without being logged into Chrome and it still comes up the same.  


{
  module: "MMM-GoogleSheets",
  header: "Speech Student and Specials Day",
  position: "middle_center",
  config: {
   
    url:  "https://script.google.com/macros/s/AKfycbzgvK0Ilmi6jaAXQdcy6SBGp9SGx9DqayB8A95d9KKs2NlzVwcUARNlyqyK-_3RtzPE/exec",
    sheet: "Sheet1",
    range: "A1:F28",
  }

},



![Screenshot 2024-09-07 at 8 06 23 AM](https://github.com/user-attachments/assets/098c8201-60cc-4ba2-9979-eb7089410ee6)

![Screenshot 2024-09-07 at 8 07 52 AM](https://github.com/user-attachments/assets/43e934d8-c159-4696-baf5-5c00e01f34fe)

**Comment by ryan-d-williams** [comment]
@brianbslp thanks for putting that together.

When I use that exact config, I am not getting any errors and can see the data on my mirror:
![image](https://github.com/user-attachments/assets/45885563-9042-4046-b25d-87a168f77d91)

Are you still receiving errors with this config? If so there is likely something else going on with your MM not related to this module. Is there an internet connection on your pi?

**Comment by brianbslp** [comment]
@ryan-d-williams I tested my internet connection by turning off the Wifi and then used a CAT6 cable to go wired to the LAN/internet.  I'm still having the same issue.  I don't believe I would have any firewall rules blocking this function.  I'm not that deep into my build so I will reload my Pi OS, reinstall MM, and try again.  Thank you for all your assistance it seems it is on my end in some way and hopefully, by reinstalling MM it will fix it.

**Comment by brianbslp** [comment]
@ryan-d-williams again thanks for your quick and amazing help!  I ended up connecting to my phone's hotspot and that did the trick.  Apparently, I must have some firewall settings blocking the communication.  Now to figure out what those are and why they would be blocking the request.

**Comment by ryan-d-williams** [comment]
@brianbslp I'm glad you got it figured out! I'm going to go ahead and close the issue but feel free to reopen if you have any more problems.
