### ISSUE TITLE
how to left align text?

### ISSUE THREAD

**Issue by GiantWheels** [ryan-d-williams/MMM-GoogleSheets#54]
Hi Ryan, great work on this stuff, I'm really enjoying using it.    However, I can't figure out how to "Left Align" text.    If I am using custom style, and then add **stylesFromSheet: ["font-size","color","font-weight","text-align"]**, I would assume that the text in the cells would be aligned according to style in the spreadsheet.  However, all I get is right-aligned text.    

It's probably not a bug, just me not understanding something.

Tx

**Comment by ryan-d-williams** [comment]
Thank you!

I'm unfortunately not able to reproduce your bug, but what you are describing sounds correct.

I made a quick example to try to reproduce it and the text was aligned as expected:
![image](https://github.com/user-attachments/assets/a700ade0-9ba1-463a-b24b-9088edbe5cca)

Note that I tried it both with and without `stylesFromSheet` and got the same results.

Are you able to share your config? If you can then I can try to take a look. If you cannot share your config because of sensitive data then you can consider removing the sensitive data before sharing the config and then redeploying after we are done debugging (redeploying changes the link).

**Comment by GiantWheels** [comment]
Thanks Ryan, I wasn't expecting you to reply so quickly!   Very impressive.  

Here's my config:

{
			module: "MMM-GoogleSheets",
			header: "Messages",
			position: "top_right",
			config: {
				url: "url here, it works",
				sheet: "Messages",
				range: "B3:D8",
				updateInterval: 2,
				requestDelay: 250,
				updateFadeSpeed: 0,
				cellStyle: "custom",
				//customStyle: ["text-align: left"],
				border: "none",
				headerStyles: ["font-weight: bold","text-align: left"],
				stylesFromSheet: ["font-size","color","font-weight","text-align"]
			}

Here's the sheet:
![screenshot_785](https://github.com/user-attachments/assets/9734987e-96b5-41ff-b140-6c85e029bdc8)


Here's whats in MM
![screenshot_786](https://github.com/user-attachments/assets/311bff43-1be7-4f68-995c-f462ce39cff3)

**Comment by ryan-d-williams** [comment]
@GiantWheels 

Thanks for giving that a try! I went ahead and reproduced your sheet/config exactly and it aligned as expected (I did not have the same issue). Before we go too far off the deep end with debugging, let's make sure everything is synced up:

If you can try changing the text in the google sheet from "Left Aligned" to something else (maybe "test") and then doing nothing else but refreshing the magic mirror. That will help us make sure that everything is synced up (for example we have the right deployment link, the right range and sheet, etc). That has bit me before.

If you try changing the text and it refreshes as expected let me know and we can try a few more things.

**Comment by ryan-d-williams** [comment]
@GiantWheels just for context, the reason I suspect there is a sync issue is because the way your MM looks. If you use `cellStyle: custom`, then the MM should not have the same cell widths as the sheet (unless you specifically force it in the config). Since your MM has the same cell widths as the Google Sheets, I think there might be some kind of sync issue. 

Another random though: don't forget you have to restart the MM each time you make a config change. A refresh does not take the new config changes.

**Comment by GiantWheels** [comment]
I've been playing with it, and it seems to depend how to set alignment in Sheets.  If I select the whole range and set the alignment it works as expected.    Lets say its not a bug on your side, thanks very much for your help.

Thanks again!
