### ISSUE TITLE
GoogleSheets disappeared from screen

### ISSUE THREAD

**Issue by oturan233** [ryan-d-williams/MMM-GoogleSheets#57]
Hi,

I was using without any problem.

Module is disappeared sudddenly. I tried to upgrade it with "git pull" and "npm i" . However nothing changed. I realized that npm version or something is older than requiered. I upgraded npm and such services, I tried to delete all directory "MMM-GoogleSheets" and reinstall it but no luck. 

Do you have any idea?

Best regards

**Comment by ryan-d-williams** [comment]
@oturan233 it's difficult to say without more information.

What are you seeing on the screen? Is it showing an error or nothing at all?

Is there an error printed in the terminal or in the browser developer console?

What does your config look like?

**Comment by oturan233** [comment]
On my screen: Every other module is working as it was. Only GoogleSheets is gone. I tried to look to the logs. I couldn't see the module in the beginning og the log. For example, all other modules are seen on log:

2024-10-23 20:39:27.441] [INFO]  Checking git for module: MMM-NBA 
[2024-10-23 20:39:27.566] [INFO]  Checking git for module: EXT-Updates 
[2024-10-23 20:39:27.696] [INFO]  Checking git for module: MMM-HTMLSnippet 
[2024-10-23 20:39:27.758] [INFO]  Checking git for module: MMM-PiTemp 
[2024-10-23 20:39:27.828] [INFO]  Checking git for module: EXT-SelfiesViewer 
[2024-10-23 20:39:27.853] [INFO]  Checking git for module: EXT-Detector 
...
...
etc..

However GoogleSheets is not in the log.

Config file is not changed. It was working for months without any problem.

**Comment by ryan-d-williams** [comment]
@oturan233 you are seeing this because you are using an old version of MM (when you first start MM, it will print the version). The new features of this module (mainly the new scrolling feature) require the newest version of MM (2.29.0).

I went ahead and removed the required version from the module file. If you update the module (do another git pull), it will work again, but you will not be able to use any of the new features until you update your MM to 2.29.0 or later.

**Comment by ryan-d-williams** [comment]
I'm going to close this for now since it should be fixed. Feel free to open it back up if you are still having problems.
