### ISSUE TITLE
MM displaying only 'Loading...' for sheets on startup

### ISSUE THREAD

**Issue by theLoganaut** [ryan-d-williams/MMM-GoogleSheets#7]
Hello, when I open the google sheets link I was given from the script page, it throws me;

TypeError: Cannot read property '0' of undefined (line 11, file "Code")

I've made sure the file is open even to anon, and I pasted your code into the google scripts page. When I open in MM it shows the header and below is just 'Loading ...'. 

Now I did use mmpm to install instead of cloning from github, which I hope isn't my issue..

**Comment by ryan-d-williams** [comment]
> TypeError: Cannot read property '0' of undefined (line 11, file "Code")
@katawatsu the reason you are getting this issue is because you cannot just click the link by itself. The module inserts parameters that are required as part of the link to get data from it.

If the data in your sheet is not sensitive / private, can you post the full config you are using? It is likely a config problem that is causing the loading issue.

**Comment by ryan-d-williams** [comment]
@theLoganaut closing this issue as it is stale. Feel free to reopen if you are still having this problem.
